Basic Functions in Pandas

In [1]:
import pandas as pd
df = pd.read_csv('fuel.csv')

Shape

In [2]:
row,col = df.shape

In [3]:
row

22

In [4]:
col

16

Top nth row

In [5]:
df.head(10)

,country,sub_region,iso3,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,South Asia,PAK,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,South Asia,IND,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,South Asia,BGD,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,South Asia,LKA,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,South Asia,NPL,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5
5,Afghanistan,South Asia,AFG,0.86,0.81,0.85,60,2.3,100,0,0.0,False,0.0,2.9,2026-04-04,43.0
6,China,East Asia,CHN,1.26,1.12,0.82,960,25.4,72,17840,10.2,False,0.0,990.0,2026-04-04,3.9
7,Japan,East Asia,JPN,1.15,1.04,1.20,3200,92.8,99,3520,3.5,True,8.2,182.0,2026-04-04,1.1
8,South Korea,East Asia,KOR,1.37,1.22,1.00,2800,68.1,97,3330,10.5,False,0.0,96.0,2026-04-04,1.5
9,Taiwan,East Asia,TWN,1.06,0.91,0.85,2200,69.2,98,1200,5.0,True,3.5,35.0,2026-04-04,1.4

Last nth row

In [6]:
df.tail(10)

,country,sub_region,iso3,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
12,Malaysia,Southeast Asia,MYS,0.46,0.86,0.50,820,59.4,35,770,2.8,True,14.2,56.0,2026-04-04,1.7
13,Indonesia,Southeast Asia,IDN,0.61,0.72,0.68,320,17.5,42,1080,0.5,True,18.5,148.0,2026-04-04,5.7
14,Vietnam,Southeast Asia,VNM,1.09,0.95,0.82,280,8.6,60,360,0.7,False,0.0,43.5,2026-04-04,11.7
15,Philippines,Southeast Asia,PHL,1.26,1.13,0.95,310,8.2,100,280,0.4,False,0.0,36.0,2026-04-04,12.2
16,Singapore,Southeast Asia,SGP,2.53,2.05,1.35,4800,63.2,100,1500,5.8,False,0.0,17.5,2026-04-04,1.6
17,Cambodia,Southeast Asia,KHM,1.27,1.17,1.02,180,4.7,100,0,0.0,False,0.0,4.8,2026-04-04,21.2
18,Myanmar,Southeast Asia,MMR,1.12,1.02,0.92,110,3.3,55,50,0.0,True,0.8,10.2,2026-04-04,30.5
19,Laos,Southeast Asia,LAO,1.32,1.16,1.08,160,4.0,100,0,0.0,False,0.0,2.4,2026-04-04,24.8
20,Brunei,Southeast Asia,BRN,0.39,0.23,0.30,2200,188.0,0,165,0.2,True,0.5,2.6,2026-04-04,0.5
21,Timor-Leste,Southeast Asia,TLS,1.38,1.32,1.15,120,2.9,100,0,0.0,False,0.0,0.4,2026-04-04,34.5

Range of entries

In [7]:
df[5:10]

,country,sub_region,iso3,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
5,Afghanistan,South Asia,AFG,0.86,0.81,0.85,60,2.3,100,0,0.0,False,0.0,2.9,2026-04-04,43.0
6,China,East Asia,CHN,1.26,1.12,0.82,960,25.4,72,17840,10.2,False,0.0,990.0,2026-04-04,3.9
7,Japan,East Asia,JPN,1.15,1.04,1.20,3200,92.8,99,3520,3.5,True,8.2,182.0,2026-04-04,1.1
8,South Korea,East Asia,KOR,1.37,1.22,1.00,2800,68.1,97,3330,10.5,False,0.0,96.0,2026-04-04,1.5
9,Taiwan,East Asia,TWN,1.06,0.91,0.85,2200,69.2,98,1200,5.0,True,3.5,35.0,2026-04-04,1.4

Accessing Column

In [8]:
df.country

0        Pakistan
1           India
2      Bangladesh
3       Sri Lanka
4           Nepal
5     Afghanistan
6           China
7           Japan
8     South Korea
9          Taiwan
10       Mongolia
11       Thailand
12       Malaysia
13      Indonesia
14        Vietnam
15    Philippines
16      Singapore
17       Cambodia
18        Myanmar
19           Laos
20         Brunei
21    Timor-Leste
Name: country, dtype: object

In [9]:
df['country']

0        Pakistan
1           India
2      Bangladesh
3       Sri Lanka
4           Nepal
5     Afghanistan
6           China
7           Japan
8     South Korea
9          Taiwan
10       Mongolia
11       Thailand
12       Malaysia
13      Indonesia
14        Vietnam
15    Philippines
16      Singapore
17       Cambodia
18        Myanmar
19           Laos
20         Brunei
21    Timor-Leste
Name: country, dtype: object

Columns

In [10]:
df.columns

Index(['country', 'sub_region', 'iso3', 'gasoline_usd_per_liter',
       'diesel_usd_per_liter', 'lpg_usd_per_kg', 'avg_monthly_income_usd',
       'fuel_affordability_index', 'oil_import_dependency_pct',
       'refinery_capacity_kbpd', 'ev_adoption_pct', 'fuel_subsidy_active',
       'subsidy_cost_bn_usd', 'co2_transport_mt', 'price_date',
       'gasoline_pct_daily_wage'],
      dtype='object')

In [11]:
df[['country','sub_region']].head()

      country  sub_region
0    Pakistan  South Asia
1       India  South Asia
2  Bangladesh  South Asia
3   Sri Lanka  South Asia
4       Nepal  South Asia

Types of column

In [12]:
type(df.country)

pandas.core.series.Series

In [13]:
type(df[['country']])

pandas.core.frame.DataFrame

Maximum value in column

In [14]:
df['avg_monthly_income_usd'].max()

4800

In [15]:
df['avg_monthly_income_usd'].min()

60

In [16]:
df['avg_monthly_income_usd'].mean()

np.float64(931.8181818181819)

In [19]:
df['avg_monthly_income_usd'].std()

1279.7047143166099

In [20]:
df['avg_monthly_income_usd'].mode()

0     120
1     160
2     180
3     280
4    2200
Name: avg_monthly_income_usd, dtype: int64

In [21]:
df['avg_monthly_income_usd'].value_counts()

avg_monthly_income_usd
180     2
160     2
120     2
280     2
2200    2
580     1
4800    1
310     1
320     1
820     1
2800    1
450     1
3200    1
960     1
60      1
210     1
110     1
Name: count, dtype: int64

In [25]:
df['avg_monthly_income_usd'].quantile()

np.float64(295.0)

In [26]:
df.describe()

,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,subsidy_cost_bn_usd,co2_transport_mt,gasoline_pct_daily_wage
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,1.178636,1.093182,0.954091,931.818182,30.577273,81.363636,1695.818182,2.163636,3.090909,95.731818,14.577273
std,0.427265,0.360137,0.252373,1279.704714,44.764430,27.830346,3871.025638,3.199337,5.140216,214.338763,13.043770
min,0.390000,0.230000,0.300000,60.000000,2.300000,0.000000,0.000000,0.000000,0.000000,0.400000,0.500000
25%,1.062500,0.935000,0.827500,165.000000,4.175000,64.500000,8.250000,0.100000,0.000000,4.425000,2.250000
50%,1.195000,1.070000,0.965000,295.000000,8.500000,98.500000,320.000000,0.450000,0.000000,26.250000,11.800000
75%,1.335000,1.185000,1.132500,925.000000,50.900000,100.000000,1305.000000,3.325000,4.775000,73.250000,23.900000
max,2.530000,2.050000,1.350000,4800.000000,188.000000,100.000000,17840.000000,10.500000,18.500000,990.000000,43.000000