Dictionary to DataFrame or Series

In [1]:
import pandas as pd

In [2]:
data = {
    'name':['rashed','sabit','prio'],
    'age':[23,24,23],
    'city':['jamalpur','serpur','rangpur']
}

In [3]:
data

{'name': ['rashed', 'sabit', 'prio'],
 'age': [23, 24, 23],
 'city': ['jamalpur', 'serpur', 'rangpur']}

In [4]:
name_series = pd.Series(data['name'],name='Name')
name_series

0    rashed
1     sabit
2      prio
Name: Name, dtype: object

In [5]:
df = pd.DataFrame(data)
df

     name  age      city
0  rashed   23  jamalpur
1   sabit   24    serpur
2    prio   23   rangpur

In [6]:
age_series = df['age']
age_series

0    23
1    24
2    23
Name: age, dtype: int64

In [7]:
city_series = df['city']
city_series

0    jamalpur
1      serpur
2     rangpur
Name: city, dtype: object

Set and Tuple to DataFrame or Series

In [11]:
s1 = {1,2,3,4,5,6,7,8,9,10}
s= pd.Series(list(s1))

In [12]:
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [13]:
df1 = pd.DataFrame(s1)
df1

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [14]:
type(df1)

pandas.core.frame.DataFrame

In [15]:
t =(1,2,3,4,5)
s2 = pd.Series(t)
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [16]:
df2 = pd.DataFrame(t)
df2

   0
0  1
1  2
2  3
3  4
4  5

In [19]:
type(df2)

pandas.core.frame.DataFrame