In [12]:
import pandas as pd

In [13]:
df =pd.read_csv("fuel.csv")

In [14]:
df.head(5)

,country,sub_region,iso3,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,South Asia,PAK,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,South Asia,IND,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,South Asia,BGD,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,South Asia,LKA,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,South Asia,NPL,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   country                    22 non-null     object
 1   sub_region                 22 non-null     object
 2   iso3                       22 non-null     object
 3   gasoline_usd_per_liter     22 non-null     float64
 4   diesel_usd_per_liter       22 non-null     float64
 5   lpg_usd_per_kg             22 non-null     float64
 6   avg_monthly_income_usd     22 non-null     int64
 7   fuel_affordability_index   22 non-null     float64
 8   oil_import_dependency_pct  22 non-null     int64
 9   refinery_capacity_kbpd     22 non-null     int64
 10  ev_adoption_pct            22 non-null     float64
 11  fuel_subsidy_active        22 non-null     bool
 12  subsidy_cost_bn_usd        22 non-null     float64
 13  co2_transport_mt           22 non-null     float64
 14  price_date                 22 non-null     object
 15  gasoline_pct_daily_wage    22 non-null     float64
dtypes: bool(1), float64(8), int64(3), object(4)
memory usage: 2.7+ KB

Delete Columns Using "del"

In [16]:
del df["iso3"]

In [17]:
df.head()

,country,sub_region,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,South Asia,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,South Asia,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,South Asia,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,South Asia,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,South Asia,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5

Delete Columns Using "pop"

In [18]:
df.pop("sub_region")

0         South Asia
1         South Asia
2         South Asia
3         South Asia
4         South Asia
5         South Asia
6          East Asia
7          East Asia
8          East Asia
9          East Asia
10         East Asia
11    Southeast Asia
12    Southeast Asia
13    Southeast Asia
14    Southeast Asia
15    Southeast Asia
16    Southeast Asia
17    Southeast Asia
18    Southeast Asia
19    Southeast Asia
20    Southeast Asia
21    Southeast Asia
Name: sub_region, dtype: object

In [19]:
df.head()

,country,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5

In [20]:
x =df.drop('ev_adoption_pct',axis=1).head()

In [21]:
x

,country,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,1.64,1.86,1.25,180,3.7,85,450,True,5.2,42.5,2026-04-04,27.3
1,India,1.11,1.03,1.08,280,8.4,85,5340,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,1.07,0.93,0.98,160,5.0,100,33,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,1.34,1.19,1.18,210,5.2,100,50,False,0.0,8.5,2026-04-04,19.1
4,Nepal,1.34,1.21,1.28,120,3.0,100,0,False,0.0,4.3,2026-04-04,33.5

In [22]:
y = df[['ev_adoption_pct']]

In [23]:
y

    ev_adoption_pct
0               0.4
1               2.4
2               0.1
3               0.2
4               0.6
5               0.0
6              10.2
7               3.5
8              10.5
9               5.0
10              0.1
11              4.2
12              2.8
13              0.5
14              0.7
15              0.4
16              5.8
17              0.0
18              0.0
19              0.0
20              0.2
21              0.0

Delete Rows

In [24]:
df.drop([0,1],axis='index')

,country,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
2,Bangladesh,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5
5,Afghanistan,0.86,0.81,0.85,60,2.3,100,0,0.0,False,0.0,2.9,2026-04-04,43.0
6,China,1.26,1.12,0.82,960,25.4,72,17840,10.2,False,0.0,990.0,2026-04-04,3.9
7,Japan,1.15,1.04,1.20,3200,92.8,99,3520,3.5,True,8.2,182.0,2026-04-04,1.1
8,South Korea,1.37,1.22,1.00,2800,68.1,97,3330,10.5,False,0.0,96.0,2026-04-04,1.5
9,Taiwan,1.06,0.91,0.85,2200,69.2,98,1200,5.0,True,3.5,35.0,2026-04-04,1.4
10,Mongolia,1.06,1.02,0.95,450,14.2,100,0,0.1,False,0.0,3.3,2026-04-04,7.1
11,Thailand,1.24,1.10,0.78,580,15.6,62,1340,4.2,True,5.8,79.0,2026-04-04,6.4
12,Malaysia,0.46,0.86,0.50,820,59.4,35,770,2.8,True,14.2,56.0,2026-04-04,1.7
13,Indonesia,0.61,0.72,0.68,320,17.5,42,1080,0.5,True,18.5,148.0,2026-04-04,5.7
14,Vietnam,1.09,0.95,0.82,280,8.6,60,360,0.7,False,0.0,43.5,2026-04-04,11.7
15,Philippines,1.26,1.13,0.95,310,8.2,100,280,0.4,False,0.0,36.0,2026-04-04,12.2
16,Singapore,2.53,2.05,1.35,4800,63.2,100,1500,5.8,False,0.0,17.5,2026-04-04,1.6
17,Cambodia,1.27,1.17,1.02,180,4.7,100,0,0.0,False,0.0,4.8,2026-04-04,21.2
18,Myanmar,1.12,1.02,0.92,110,3.3,55,50,0.0,True,0.8,10.2,2026-04-04,30.5
19,Laos,1.32,1.16,1.08,160,4.0,100,0,0.0,False,0.0,2.4,2026-04-04,24.8
20,Brunei,0.39,0.23,0.30,2200,188.0,0,165,0.2,True,0.5,2.6,2026-04-04,0.5
21,Timor-Leste,1.38,1.32,1.15,120,2.9,100,0,0.0,False,0.0,0.4,2026-04-04,34.5

In [25]:
d = df[df['gasoline_usd_per_liter']>1]

In [26]:
d

,country,gasoline_usd_per_liter,diesel_usd_per_liter,lpg_usd_per_kg,avg_monthly_income_usd,fuel_affordability_index,oil_import_dependency_pct,refinery_capacity_kbpd,ev_adoption_pct,fuel_subsidy_active,subsidy_cost_bn_usd,co2_transport_mt,price_date,gasoline_pct_daily_wage
0,Pakistan,1.64,1.86,1.25,180,3.7,85,450,0.4,True,5.2,42.5,2026-04-04,27.3
1,India,1.11,1.03,1.08,280,8.4,85,5340,2.4,True,8.5,325.0,2026-04-04,11.9
2,Bangladesh,1.07,0.93,0.98,160,5.0,100,33,0.1,True,2.8,16.2,2026-04-04,20.1
3,Sri Lanka,1.34,1.19,1.18,210,5.2,100,50,0.2,False,0.0,8.5,2026-04-04,19.1
4,Nepal,1.34,1.21,1.28,120,3.0,100,0,0.6,False,0.0,4.3,2026-04-04,33.5
6,China,1.26,1.12,0.82,960,25.4,72,17840,10.2,False,0.0,990.0,2026-04-04,3.9
7,Japan,1.15,1.04,1.20,3200,92.8,99,3520,3.5,True,8.2,182.0,2026-04-04,1.1
8,South Korea,1.37,1.22,1.00,2800,68.1,97,3330,10.5,False,0.0,96.0,2026-04-04,1.5
9,Taiwan,1.06,0.91,0.85,2200,69.2,98,1200,5.0,True,3.5,35.0,2026-04-04,1.4
10,Mongolia,1.06,1.02,0.95,450,14.2,100,0,0.1,False,0.0,3.3,2026-04-04,7.1
11,Thailand,1.24,1.10,0.78,580,15.6,62,1340,4.2,True,5.8,79.0,2026-04-04,6.4
14,Vietnam,1.09,0.95,0.82,280,8.6,60,360,0.7,False,0.0,43.5,2026-04-04,11.7
15,Philippines,1.26,1.13,0.95,310,8.2,100,280,0.4,False,0.0,36.0,2026-04-04,12.2
16,Singapore,2.53,2.05,1.35,4800,63.2,100,1500,5.8,False,0.0,17.5,2026-04-04,1.6
17,Cambodia,1.27,1.17,1.02,180,4.7,100,0,0.0,False,0.0,4.8,2026-04-04,21.2
18,Myanmar,1.12,1.02,0.92,110,3.3,55,50,0.0,True,0.8,10.2,2026-04-04,30.5
19,Laos,1.32,1.16,1.08,160,4.0,100,0,0.0,False,0.0,2.4,2026-04-04,24.8
21,Timor-Leste,1.38,1.32,1.15,120,2.9,100,0,0.0,False,0.0,0.4,2026-04-04,34.5

Rename and ConCate DataFrame

In [27]:
df1 =pd.DataFrame({'AGE':[10,20],'INCOME':[1000,2000]})
df2 =pd.DataFrame({'AGE':[30,40],'INCOME':[10000,20000]})

In [28]:
df1

   AGE  INCOME
0   10    1000
1   20    2000

In [29]:
df2

   AGE  INCOME
0   30   10000
1   40   20000

In [30]:
df1 = df1.rename(columns ={'AGE':'age','INCOME':'income'})
df2 = df2.rename(columns ={'AGE':'age','INCOME':'income'})

In [31]:
df1

   age  income
0   10    1000
1   20    2000

In [32]:
df2

   age  income
0   30   10000
1   40   20000

In [33]:
result = pd.concat([df1,df2],axis=1)
result

   age  income  age  income
0   10    1000   30   10000
1   20    2000   40   20000

In [34]:
rs = pd.concat([df1,df2])
rs

   age  income
0   10    1000
1   20    2000
0   30   10000
1   40   20000

NaN Value

In [35]:
dff = pd.read_excel("NaN_data.xlsx")
dff

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   NaN      NaN
3  1400.0   3.0  21010.0
4  1200.0   NaN  20100.0
5     NaN   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

In [38]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    8 non-null      float64
 1   room    7 non-null      float64
 2   rent    8 non-null      float64
dtypes: float64(3)
memory usage: 348.0 bytes

In [42]:
pd.isna(dff).sum()

area    1
room    2
rent    1
dtype: int64

In [43]:
pd.isna(dff)

    area   room   rent
0  False  False  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False   True  False
5   True  False  False
6  False  False  False
7  False  False  False
8  False  False  False

In [41]:
pd.isnull(dff)

    area   room   rent
0  False  False  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False   True  False
5   True  False  False
6  False  False  False
7  False  False  False
8  False  False  False

In [44]:
pd.isnull(dff).sum()

area    1
room    2
rent    1
dtype: int64