Objects & DateTime Datatype

In [2]:
import pandas as pd

In [3]:

dates =['2026-10-04','2026-10-04','2026-10-04']
df =pd.DataFrame({'Date': dates})

In [4]:
df

         Date
0  2026-10-04
1  2026-10-04
2  2026-10-04

In [5]:
timestamps = pd.to_datetime(dates)

In [6]:
df2 = pd.DataFrame({'Date2': timestamps})

In [7]:
df2

       Date2
0 2026-10-04
1 2026-10-04
2 2026-10-04

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date2   3 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 156.0 bytes