Handle Misssing Data

In [1]:
import pandas as pd
df = pd.read_excel('NaN_data.xlsx')

In [2]:
df

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   NaN      NaN
3  1400.0   3.0  21010.0
4  1200.0   NaN  20100.0
5     NaN   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

Filling the data with 0 value

In [3]:
df.fillna(0,inplace=True)

In [5]:
df.isnull().sum()

area    0
room    0
rent    0
dtype: int64

In [9]:
df

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   0.0      0.0
3  1400.0   3.0  21010.0
4  1200.0   0.0  20100.0
5     0.0   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

In [18]:
df.dropna()

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   0.0      0.0
3  1400.0   3.0  21010.0
4  1200.0   0.0  20100.0
5     0.0   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

Fill values with central tandency

In [29]:
dfff = pd.read_excel('NaN_data.xlsx')
dfff

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   NaN      NaN
3  1400.0   3.0  21010.0
4  1200.0   NaN  20100.0
5     NaN   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

In [32]:
dfff.fillna(dfff.mean())

     area      room      rent
0  1000.0  3.000000  21000.00
1  1200.0  3.000000  20000.00
2  1350.0  3.285714  20956.25
3  1400.0  3.000000  21010.00
4  1200.0  3.285714  20100.00
5  1215.0  4.000000  23170.00
6  1000.0  3.000000  21000.00
7  1220.0  3.000000  21000.00
8  1350.0  4.000000  20370.00

In [31]:
dfff.mean()

area     1215.000000
room        3.285714
rent    20956.250000
dtype: float64

In [33]:
dfff.fillna(dfff.median())

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   3.0  21000.0
3  1400.0   3.0  21010.0
4  1200.0   3.0  20100.0
5  1210.0   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

In [34]:
dfff.median()

area     1210.0
room        3.0
rent    21000.0
dtype: float64

In [35]:
dfff.fillna(dfff.mode())

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   3.0  20000.0
2  1350.0   NaN      NaN
3  1400.0   3.0  21010.0
4  1200.0   NaN  20100.0
5     NaN   4.0  23170.0
6  1000.0   3.0  21000.0
7  1220.0   3.0  21000.0
8  1350.0   4.0  20370.0

In [36]:
dfff.mode()

     area  room     rent
0  1000.0   3.0  21000.0
1  1200.0   NaN      NaN
2  1350.0   NaN      NaN